#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/llava_onevision/modular_llava_onevision.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_llava_onevision.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# coding=utf-8
# Copyright 2024 the HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import json
import logging
import math
from dataclasses import dataclass
from typing import Optional, Union, List, Dict

import numpy as np
import torch
import torch.nn.functional as F_torch
from torch import nn
from transformers import PreTrainedModel, LlavaOnevisionConfig, AutoModel, GenerationMixin
from transformers.activations import ACT2FN
from transformers.cache_utils import Cache
from transformers.image_processing_utils import select_best_resolution
from transformers.modeling_flash_attention_utils import FlashAttentionKwargs
from transformers.modeling_outputs import BaseModelOutputWithPast, ModelOutput
from transformers.processing_utils import Unpack
from transformers.utils import auto_docstring, can_return_tuple, TransformersKwargs

logger = logging.getLogger(__name__)

@dataclass
@auto_docstring(
    custom_intro="""
    Base class for Llava outputs, with hidden states and attentions.
    """
)
class LlavaOnevisionModelOutputWithPast(BaseModelOutputWithPast):
    r"""
    past_key_values (`Cache`, *optional*, returned when `use_cache=True` is passed or when `config.use_cache=True`):
        It is a [`~cache_utils.Cache`] instance. For more details, see our [kv cache guide](https://huggingface.co/docs/transformers/en/kv_cache).

        Contains pre-computed hidden-states (key and values in the self-attention blocks) that can be used (see
        `past_key_values` input) to speed up sequential decoding.
    image_hidden_states (`torch.FloatTensor`, *optional*):
        A `torch.FloatTensor` of size `(batch_size, num_images, sequence_length, hidden_size)`.
        image_hidden_states of the model produced by the vision encoder and after projecting the last hidden state.
    video_hidden_states (`torch.FloatTensor`, *optional*):
        A `torch.FloatTensor`  of size `(batch_size * num_frames, num_videos, sequence_length, hidden_size)`.
        video_hidden_states of the model produced by the vision encoder and after projecting the last hidden state.
    """

    image_hidden_states: Optional[torch.FloatTensor] = None

    video_hidden_states: Optional[torch.FloatTensor] = None


@dataclass
@auto_docstring(
    custom_intro="""
    Base class for LlavaOnevision causal language model (or autoregressive) outputs.
    """
)
class LlavaOnevisionCausalLMOutputWithPast(ModelOutput):
    r"""
    loss (`torch.FloatTensor` of shape `(1,)`, *optional*, returned when `labels` is provided):
        Language modeling loss (for next-token prediction).
    logits (`torch.FloatTensor` of shape `(batch_size, sequence_length, config.vocab_size)`):
        Prediction scores of the language modeling head (scores for each vocabulary token before SoftMax).
    past_key_values (`Cache`, *optional*, returned when `use_cache=True` is passed or when `config.use_cache=True`):
        It is a [`~cache_utils.Cache`] instance. For more details, see our [kv cache guide](https://huggingface.co/docs/transformers/en/kv_cache).

        Contains pre-computed hidden-states (key and values in the self-attention blocks) that can be used (see
        `past_key_values` input) to speed up sequential decoding.
    image_hidden_states (`torch.FloatTensor`, *optional*):
        A `torch.FloatTensor` of size (batch_size * num_patches, num_images, sequence_length, hidden_size)`.
        image_hidden_states of the model produced by the vision encoder and after projecting the last hidden state.
    video_hidden_states (`torch.FloatTensor`, *optional*):
        A `torch.FloatTensor`  of size `(batch_size * num_frames, num_videos, sequence_length, hidden_size)`.
        video_hidden_states of the model produced by the vision encoder and after projecting the last hidden state.
    """

    loss: Optional[torch.FloatTensor] = None
    logits: Optional[torch.FloatTensor] = None
    past_key_values: Optional[Cache] = None
    hidden_states: Optional[tuple[torch.FloatTensor]] = None
    attentions: Optional[tuple[torch.FloatTensor]] = None
    image_hidden_states: Optional[torch.FloatTensor] = None

    video_hidden_states: Optional[torch.FloatTensor] = None


@auto_docstring
class LlavaOnevisionPreTrainedModel(PreTrainedModel):
    config: LlavaOnevisionConfig
    base_model_prefix = ""
    supports_gradient_checkpointing = True
    _no_split_modules = ["LlamaDecoderLayer"]
    _skip_keys_device_placement = "past_key_values"

    _supports_flash_attn = True
    _supports_sdpa = True

    _can_compile_fullgraph = True
    _supports_flex_attn = True
    _supports_attention_backend = True

    def _init_weights(self, module):
        std = getattr(self.config, "initializer_range", self.config.get_text_config().initializer_range)

        if isinstance(module, nn.Linear):
            module.weight.data.normal_(mean=0.0, std=std)
            if module.bias is not None:
                module.bias.data.zero_()
        elif isinstance(module, LlavaOnevisionModel):
            embed_std = 1 / math.sqrt(self.config.text_config.hidden_size)
            module.image_newline.data.normal_(mean=0.0, std=embed_std)


class LlavaOnevisionMultiModalProjector(nn.Module):
    def __init__(self, config: LlavaOnevisionConfig):
        super().__init__()
        # We have hidden_size * the number of vision feature layers
        num_feature_layers = 1 if isinstance(config.vision_feature_layer, int) else len(config.vision_feature_layer)
        self.linear_1 = nn.Linear(
            config.vision_config.hidden_size * num_feature_layers,
            config.text_config.hidden_size,
            bias=config.multimodal_projector_bias,
        )
        self.act = ACT2FN[config.projector_hidden_act]
        self.linear_2 = nn.Linear(
            config.text_config.hidden_size, config.text_config.hidden_size, bias=config.multimodal_projector_bias
        )

    def forward(self, image_features):
        hidden_states = self.linear_1(image_features)
        hidden_states = self.act(hidden_states)
        hidden_states = self.linear_2(hidden_states)
        return hidden_states


def get_anyres_image_grid_shape(image_size, grid_pinpoints, patch_size):
    """
    Calculate the shape of the image patch grid after the preprocessing for images of any resolution.

    Args:
        image_size (`tuple`):
            The size of the input image in the format (width, height).
        grid_pinpoints (`List`):
            A list containing possible resolutions. Each item in the list should be a tuple or list
            of the form `(height, width)`.
        patch_size (`int`):
            The size of each image patch.

    Returns:
        tuple: The shape of the image patch grid in the format (width, height).
    """
    if not isinstance(grid_pinpoints, list):
        raise TypeError("grid_pinpoints should be a list of tuples or lists")

    # ! VERY IMPORTANT if image_size is tensor, must convert to into tuple, otherwise it will cause wrong calculate
    if not isinstance(image_size, (list, tuple)):
        if not isinstance(image_size, (torch.Tensor, np.ndarray)):
            raise TypeError(
                f"image_size invalid type: {type(image_size)} not valid, should be either list, tuple, np.ndarray or tensor"
            )
        image_size = image_size.tolist()

    height, width = select_best_resolution(image_size, grid_pinpoints)
    return height // patch_size, width // patch_size


def image_size_to_num_patches(image_size, grid_pinpoints, patch_size: int):
    """
    Calculate the number of patches after the preprocessing for images of any resolution.

    Args:
        image_size (`torch.LongTensor` or `np.ndarray` or `tuple[int, int]`):
            The size of the input image in the format (height, width). ?
        grid_pinpoints (`List`):
            A list containing possible resolutions. Each item in the list should be a tuple or list
            of the form `(height, width)`.
        patch_size (`int`):
            The size of each image patch.

    Returns:
        int: the number of patches
    """
    if not isinstance(grid_pinpoints, list):
        raise TypeError("grid_pinpoints should be a list of tuples or lists")

    # ! VERY IMPORTANT if image_size is tensor, must convert to into tuple, otherwise it will cause wrong calculate
    if not isinstance(image_size, (list, tuple)):
        if not isinstance(image_size, (torch.Tensor, np.ndarray)):
            raise TypeError(f"image_size invalid type {type(image_size)} with value {image_size}")
        image_size = image_size.tolist()

    best_resolution = select_best_resolution(image_size, grid_pinpoints)
    height, width = best_resolution
    num_patches = 0
    # consider change to ceil(height/patch_size)*ceil(width/patch_size) + 1
    for i in range(0, height, patch_size):
        for j in range(0, width, patch_size):
            num_patches += 1
    # add the base patch
    num_patches += 1
    return num_patches


def unpad_image(tensor, original_size):
    """
    Unpads a PyTorch tensor of a padded and resized image.

    Args:
        tensor (`torch.Tensor`):
            The image tensor, assumed to be of shape (num_channels, height, width).
        original_size (`tuple`):
            The original size of the image (height, width).

    Returns:
        `torch.Tensor`: The unpadded image tensor.
    """
    if not isinstance(original_size, (list, tuple)):
        if not isinstance(original_size, (torch.Tensor, np.ndarray)):
            raise TypeError(
                f"image_size invalid type: {type(original_size)} not valid, should be either list, tuple, np.ndarray or tensor"
            )
        original_size = original_size.tolist()
    original_height, original_width = original_size
    current_height, current_width = tensor.shape[1:]

    original_aspect_ratio = original_width / original_height
    current_aspect_ratio = current_width / current_height

    if original_aspect_ratio > current_aspect_ratio:
        scale_factor = current_width / original_width
        new_height = int(round(original_height * scale_factor, 7))
        padding = (current_height - new_height) // 2
        unpadded_tensor = tensor[:, padding : current_height - padding, :]
    else:
        scale_factor = current_height / original_height
        new_width = int(round(original_width * scale_factor, 7))
        padding = (current_width - new_width) // 2
        unpadded_tensor = tensor[:, :, padding : current_width - padding]

    return unpadded_tensor


@auto_docstring(
    custom_intro="""
    The Llava-Next model which consists of a vision backbone and a language model without language modeling head.
    """
)
class LlavaOnevisionModel(LlavaOnevisionPreTrainedModel):
    _checkpoint_conversion_mapping = {"language_model.model": "language_model"}

    def __init__(self, config):
        super().__init__(config)
        self.vision_tower = AutoModel.from_config(config.vision_config)

        self.multi_modal_projector = LlavaOnevisionMultiModalProjector(config)
        embed_std = 1 / math.sqrt(config.text_config.hidden_size)
        self.image_newline = nn.Parameter(torch.randn(config.text_config.hidden_size, dtype=self.dtype) * embed_std)

        self.vocab_size = config.text_config.vocab_size
        self.language_model = AutoModel.from_config(config.text_config)
        self.pad_token_id = self.config.pad_token_id if self.config.pad_token_id is not None else -1
        self.post_init()

        # ------------------------------------------------------------------
        # Semantic-oriented token pruning (SemVID) hyperparameters
        # ------------------------------------------------------------------
        self.enable_semantic_prune = getattr(config, "enable_semantic_prune", True)

        # DySeg (Stage-1 temporal segmentation)
        self.fastvid_DySeg_c = getattr(config, "fastvid_DySeg_c", 0)
        self.fastvid_DySeg_tau = getattr(config, "fastvid_DySeg_tau", 0)

        # Stage-1 budget allocation
        self.semantic_retention_ratio = getattr(config, "semantic_retention_ratio", 0.10)
        self.semantic_stage1_topk_segments = getattr(config, "semantic_stage1_topk_segments", 0)
        self.semantic_stage1_smooth_win = getattr(config, "semantic_stage1_smooth_win", 1)
        self.semantic_frame_weight_alpha = getattr(config, "semantic_frame_weight_alpha", 0.7)

        # Stage-2 semantic selection
        self.semantic_obj_ratio = getattr(config, "semantic_obj_ratio", 0.6)
        self.semantic_mmr_lambda = getattr(config, "semantic_mmr_lambda", 0.9)
        self.semantic_motion_query_beta = getattr(config, "semantic_motion_query_beta", 0.5)

        # Coherence safeguards / ablations
        self.semantic_min_tokens_per_frame = getattr(config, "semantic_min_tokens_per_frame", 0)
        self.semantic_query_token_max = getattr(config, "semantic_query_token_max", 128)
        self.ablation_uniform_allocation = getattr(config, "ablation_uniform_allocation", False)
        self.ablation_use_semantic_selection = getattr(config, "ablation_use_semantic_selection", "semvid")
        self.semantic_return_coords = getattr(config, "semantic_return_coords", 0)

        # FastVID baseline params (only used when ablation_use_semantic_selection == "fastvid")
        self.fastvid_STPrune_d = getattr(config, "fastvid_STPrune_d", 0)
        self.fastvid_DTM_p = getattr(config, "fastvid_DTM_p", 0)

        hyperparameters = {
            "enable_semantic_prune": self.enable_semantic_prune,
            "fastvid_DySeg_c": self.fastvid_DySeg_c,
            "fastvid_DySeg_tau": self.fastvid_DySeg_tau,
            "semantic_retention_ratio": self.semantic_retention_ratio,
            "semantic_min_tokens_per_frame": self.semantic_min_tokens_per_frame,
            "semantic_stage1_topk_segments": self.semantic_stage1_topk_segments,
            "semantic_stage1_smooth_win": self.semantic_stage1_smooth_win,
            "semantic_frame_weight_alpha": self.semantic_frame_weight_alpha,
            "semantic_obj_ratio": self.semantic_obj_ratio,
            "semantic_mmr_lambda": self.semantic_mmr_lambda,

            "semantic_query_token_max": self.semantic_query_token_max,
            "semantic_motion_query_beta": self.semantic_motion_query_beta,
            "ablation_uniform_allocation": self.ablation_uniform_allocation,
            "ablation_use_semantic_selection": self.ablation_use_semantic_selection,
        }
        logger.info(f"Hyperparameters for Semantic-oriented Pruning: {hyperparameters}")

        # Runtime metrics (updated on each forward when pruning is enabled)
        self.fastvid_last_stats = {}
        self.last_semantic_prune_coords = None

    def get_input_embeddings(self):
        return self.language_model.get_input_embeddings()

    def set_input_embeddings(self, value):
        self.language_model.set_input_embeddings(value)

    def set_decoder(self, decoder):
        self.language_model = decoder

    def get_decoder(self):
        return self.language_model

    def pack_image_features(self, image_features, image_sizes, image_newline=None, vision_aspect_ratio="anyres_max_9"):
        """
        Reshape, unpad and then pack each image_feature into a single image_features tensor containing all visual vectors.

        Args:
            image_features (`list[torch.Tensor]` of length num_images, each of shape `(num_patches, image_length, embed_dim)`)
                List of image feature tensor, each contains all the visual feature of all patches.
            image_sizes (`torch.Tensor` of shape `(num_images, 2)`)
                Actual image size of each images (H, W).
            image_newline (`torch.Tensor` of shape `(embed_dim)`)
                New line embedding vector.
            vision_aspect_ratio (`str`, *optional*, "anyres_max_9"):
                Aspect ratio used when processong image features. The default value is "anyres_max_9".
        Returns:
            image_features (`torch.Tensor` of shape `(all_feat_len, embed_dim)`)
            feature_lens (`list[int]`)
                token length of each image in image_features
        """
        new_image_features = []
        feature_lens = []
        for image_idx, image_feature in enumerate(image_features):
            if image_feature.shape[0] > 1:
                base_image_feature = image_feature[0]
                image_feature = image_feature[1:]
                height = width = self.config.vision_config.image_size // self.config.vision_config.patch_size
                if height * width != base_image_feature.shape[0]:
                    raise ValueError("The number of patches is not consistent with the image size.")
                num_patch_height, num_patch_width = get_anyres_image_grid_shape(
                    image_sizes[image_idx],
                    self.config.image_grid_pinpoints,
                    self.config.vision_config.image_size,
                )
                image_feature = image_feature.view(num_patch_height, num_patch_width, height, width, -1)
                image_feature = image_feature.permute(4, 0, 2, 1, 3).contiguous()
                image_feature = image_feature.flatten(1, 2).flatten(2, 3)
                image_feature = unpad_image(image_feature, image_sizes[image_idx])
                max_num_patches = int(vision_aspect_ratio.strip("anyres_max_"))
                channels, curr_height, curr_width = image_feature.shape
                ratio = math.sqrt(curr_height * curr_width / (max_num_patches * height**2))
                if ratio > 1.1:
                    image_feature = image_feature[None]
                    image_feature = nn.functional.interpolate(
                        image_feature, [int(curr_height // ratio), int(curr_width // ratio)], mode="bilinear"
                    )[0]
                if image_newline is not None:
                    image_feature = torch.cat(
                        (
                            image_feature,
                            image_newline[:, None, None]
                            .expand(*image_feature.shape[:-1], 1)
                            .to(image_feature.device, image_feature.dtype),
                        ),
                        dim=-1,
                    )
                image_feature = image_feature.flatten(1, 2).transpose(0, 1)
                image_feature = torch.cat((base_image_feature, image_feature), dim=0)
            else:
                image_feature = image_feature[0]
                if image_newline is not None:
                    image_feature = torch.cat((image_feature, image_newline[None].to(image_feature)), dim=0)
            new_image_features.append(image_feature)
            feature_lens.append(image_feature.size(0))
        feature_lens = torch.tensor(feature_lens, dtype=torch.long, device=image_features[0].device)
        return new_image_features, feature_lens

    def get_image_features(
        self,
        pixel_values: torch.FloatTensor,
        image_sizes: torch.Tensor,
        vision_feature_layer: Optional[Union[int, list[int]]] = None,
        vision_feature_select_strategy: Optional[str] = None,
        vision_aspect_ratio: Optional[str] = None,
        batch_num_images: Optional[torch.LongTensor] = None,
    ):
        """
        Obtains image last hidden states from the vision tower and apply multimodal projection.

        Args:
            pixel_values (`torch.FloatTensor]` of shape `(batch_size, num_patches, channels, height, width)`)
               The tensors corresponding to the input images.
            image_sizes (`torch.Tensor` of shape `(num_images, 2)`)
                Actual image size of each images (H, W).
            vision_feature_layer (`Union[int, list[int]]`):
                The index of the layer to select the vision feature. If multiple indices are provided,
                the vision feature of the corresponding indices will be concatenated to form the
                vision features.
            vision_feature_select_strategy (`str`):
                The feature selection strategy used to select the vision feature from the vision backbone.
                Can be one of `"default"` or `"full"`
            batch_num_images (`torch.LongTensor`, *optional*):
                Number of images in each sample.
        Returns:
            image_features (list[`torch.Tensor`]): List of image feature tensor, each contains all the visual feature of all patches
            and are of shape `(num_patches, image_length, embed_dim)`).
        """
        vision_feature_layer = (
            vision_feature_layer if vision_feature_layer is not None else self.config.vision_feature_layer
        )
        vision_feature_select_strategy = (
            vision_feature_select_strategy
            if vision_feature_select_strategy is not None
            else self.config.vision_feature_select_strategy
        )
        vision_aspect_ratio = (
            vision_aspect_ratio if vision_aspect_ratio is not None else self.config.vision_aspect_ratio
        )

        # ! infer image_num_patches from image_sizes
        if batch_num_images is None:
            # treat this as a single-image case for backward compatibility
            need_patching = [True] * len(image_sizes)
        else:
            need_patching = [n == 1 for n in batch_num_images for _ in range(n)]
        image_num_patches = [
            image_size_to_num_patches(
                image_size=imsize,
                grid_pinpoints=self.config.image_grid_pinpoints,
                patch_size=self.config.vision_config.image_size,
            )
            if should_patch
            else 1
            for imsize, should_patch in zip(image_sizes, need_patching)
        ]
        if pixel_values.dim() == 5:
            # stacked if input is (batch_size, num_patches, num_channels, height, width)
            _pixel_values_list = [pix_val[:num_patch] for pix_val, num_patch in zip(pixel_values, image_num_patches)]
            pixel_values = torch.cat(_pixel_values_list, dim=0)
        elif pixel_values.dim() != 4:
            # otherwise has to be stacked from list of (num_patches, num_channels, height, width)
            raise ValueError(f"pixel_values of shape {pixel_values.shape}, expect to be of 4 or 5 dimensions")

        image_features = self.vision_tower(pixel_values, output_hidden_states=True)
        # If we have one vision feature layer, return the corresponding hidden states,
        # otherwise, select the hidden states of each feature layer and concatenate them
        if isinstance(vision_feature_layer, int):
            selected_image_feature = image_features.hidden_states[vision_feature_layer]
        else:
            hs_pool = [image_features.hidden_states[layer_idx] for layer_idx in vision_feature_layer]
            selected_image_feature = torch.cat(hs_pool, dim=-1)

        if vision_feature_select_strategy == "default":
            selected_image_feature = selected_image_feature[:, 1:]
        image_features = self.multi_modal_projector(selected_image_feature)
        image_features = torch.split(image_features, image_num_patches, dim=0)

        image_features, feature_lens = self.pack_image_features(
            image_features,
            image_sizes,
            image_newline=self.image_newline,
            vision_aspect_ratio=vision_aspect_ratio,
        )
        return image_features

    def get_placeholder_mask(
        self,
        input_ids: torch.LongTensor,
        inputs_embeds: torch.FloatTensor,
        image_features: Optional[torch.FloatTensor] = None,
        video_features: Optional[torch.FloatTensor] = None,
    ):
        """
        Obtains multimodal placeholder mask from `input_ids` or `inputs_embeds`, and checks that the placeholder token count is
        equal to the length of multimodal features. If the lengths are different, an error is raised.
        """
        if input_ids is None:
            special_image_mask = inputs_embeds == self.get_input_embeddings()(
                torch.tensor(self.config.image_token_id, dtype=torch.long, device=inputs_embeds.device)
            )
            special_image_mask = special_image_mask.all(-1)
            special_video_mask = inputs_embeds == self.get_input_embeddings()(
                torch.tensor(self.config.video_token_id, dtype=torch.long, device=inputs_embeds.device)
            )
            special_video_mask = special_video_mask.all(-1)
        else:
            special_image_mask = input_ids == self.config.image_token_id
            special_video_mask = input_ids == self.config.video_token_id

        n_image_tokens = special_image_mask.sum()
        special_image_mask = special_image_mask.unsqueeze(-1).expand_as(inputs_embeds).to(inputs_embeds.device)
        if image_features is not None and inputs_embeds[special_image_mask].numel() != image_features.numel():
            raise ValueError(
                f"Image features and image tokens do not match: tokens: {n_image_tokens}, features {image_features.shape[0]}"
            )

        n_video_tokens = special_video_mask.sum()
        special_video_mask = special_video_mask.unsqueeze(-1).expand_as(inputs_embeds).to(inputs_embeds.device)
        if video_features is not None and inputs_embeds[special_video_mask].numel() != video_features.numel():
            raise ValueError(
                f"Videos features and image tokens do not match: tokens: {n_video_tokens}, features {video_features.shape[0]}"
            )

        return special_image_mask, special_video_mask

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        pixel_values: Optional[torch.FloatTensor] = None,
        image_sizes: Optional[torch.LongTensor] = None,
        pixel_values_videos: Optional[torch.FloatTensor] = None,
        image_sizes_videos: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        vision_feature_layer: Optional[Union[int, list[int]]] = None,
        vision_feature_select_strategy: Optional[str] = None,
        vision_aspect_ratio: Optional[str] = None,
        batch_num_images: Optional[torch.LongTensor] = None,
        query_ids: Optional[torch.LongTensor] = None,
        query_attention_mask: Optional[torch.Tensor] = None,
        use_cache: Optional[bool] = None,
        output_attentions: Optional[bool] = None,
        output_hidden_states: Optional[bool] = None,
        return_dict: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        **kwargs: Unpack[FlashAttentionKwargs],
    ) -> Union[tuple, LlavaOnevisionModelOutputWithPast]:
        r"""
        image_sizes_videos (`torch.LongTensor` of shape `(batch_size, frames, 2)`, *optional*):
            The sizes of the videos in the batch, being (height, width) for each frame in the video.
        vision_aspect_ratio (`str`, *optional*, defaults to `"anyres_max_9"`):
            Aspect ratio used when processong image features. The default value is "anyres_max_9".
        batch_num_images (`torch.LongTensor`, *optional*):
            Number of images in each sample.
        """

        output_attentions = output_attentions if output_attentions is not None else self.config.output_attentions
        output_hidden_states = (
            output_hidden_states if output_hidden_states is not None else self.config.output_hidden_states
        )
        return_dict = return_dict if return_dict is not None else self.config.use_return_dict
        vision_feature_layer = (
            vision_feature_layer if vision_feature_layer is not None else self.config.vision_feature_layer
        )
        vision_feature_select_strategy = (
            vision_feature_select_strategy
            if vision_feature_select_strategy is not None
            else self.config.vision_feature_select_strategy
        )
        vision_aspect_ratio = (
            vision_aspect_ratio if vision_aspect_ratio is not None else self.config.vision_aspect_ratio
        )

        if (input_ids is None) ^ (inputs_embeds is not None):
            raise ValueError("You must specify exactly one of input_ids or inputs_embeds")

        if inputs_embeds is None:
            inputs_embeds = self.get_input_embeddings()(input_ids)

        # ------------------------------------------------------------------
        # SemVID (semantic-oriented video token pruning) bookkeeping
        # ------------------------------------------------------------------
        num_video_frames = None
        video_tokens_per_frame = None

        # Images are processed with Anyres
        if pixel_values is not None:
            image_features = self.get_image_features(
                pixel_values,
                image_sizes,
                vision_feature_layer=vision_feature_layer,
                vision_feature_select_strategy=vision_feature_select_strategy,
                batch_num_images=batch_num_images,
            )
            image_features = torch.cat(image_features, dim=0)
            image_features = image_features.to(inputs_embeds.device, inputs_embeds.dtype)
            special_image_mask, _ = self.get_placeholder_mask(
                input_ids, inputs_embeds=inputs_embeds, image_features=image_features
            )
            inputs_embeds = inputs_embeds.masked_scatter(special_image_mask, image_features)

        # Video are simply embedded and further pooled to decrease seq len
        if pixel_values_videos is not None:
            video_features = self.get_video_features(
                pixel_values_videos,
                vision_feature_layer=vision_feature_layer,
                vision_feature_select_strategy=vision_feature_select_strategy,
            )

            # SemVID: infer per-frame token count after pooling (P) and number of frames (T)
            num_video_frames = pixel_values_videos.shape[1]
            if num_video_frames is not None and int(num_video_frames) > 0:
                video_tokens_per_frame = int(video_features.shape[1] // int(num_video_frames))
            else:
                video_tokens_per_frame = None

            image_newline = (
                self.image_newline[None, None, :].repeat(video_features.shape[0], 1, 1).to(video_features.device)
            )
            video_features = torch.cat((video_features, image_newline), dim=1)
            video_features = video_features.flatten(0, 1).to(inputs_embeds.device, inputs_embeds.dtype)
            _, special_video_mask = self.get_placeholder_mask(
                input_ids, inputs_embeds=inputs_embeds, video_features=video_features
            )
            inputs_embeds = inputs_embeds.masked_scatter(special_video_mask, video_features)


        # ------------------------------------------------------------------
        # SemVID: semantic-oriented video token pruning (optional)
        # ------------------------------------------------------------------
        if (
            getattr(self, "enable_semantic_prune", 0)
            and pixel_values_videos is not None
            and input_ids is not None
            and (video_tokens_per_frame is not None)
            and (num_video_frames is not None)
            and int(video_tokens_per_frame) > 0
            and int(num_video_frames) > 0
            and inputs_embeds is not None
            and inputs_embeds.shape[1] > 1
            and (attention_mask is None or (isinstance(attention_mask, torch.Tensor) and attention_mask.dim() == 2))
        ):
            device = inputs_embeds.device
            B, S0, D = inputs_embeds.shape
            vid_id = self.config.video_token_id

            # Only prune in prefill stage (no past kv)
            past_len = 0
            if past_key_values is not None and hasattr(past_key_values, "get_seq_length"):
                try:
                    past_len = int(past_key_values.get_seq_length())
                except Exception:
                    past_len = 0

            if past_len == 0:
                attn2d = attention_mask
                if attn2d is None:
                    attn2d = torch.ones((B, S0), dtype=torch.long, device=device)
                else:
                    attn2d = attn2d.to(device=device)
                    if attn2d.dtype == torch.bool:
                        attn2d = attn2d.to(dtype=torch.long)
                    elif attn2d.dtype != torch.long:
                        attn2d = attn2d.to(dtype=torch.long)

                new_embeds_list: List[torch.Tensor] = []
                new_mask_list: List[torch.Tensor] = []
                new_pos_list: Optional[List[torch.Tensor]] = [] if position_ids is not None else None

                kept_video_counts: List[int] = []
                orig_video_counts: List[int] = []
                semantic_prune_coords_batch: List[Optional[dict]] = []

                T = int(num_video_frames)
                P = int(video_tokens_per_frame)
                patch_len = int(T * P)

                for b in range(B):
                    valid_mask = attn2d[b].bool()

                    # Absolute positions of video placeholder tokens in the sequence
                    vid_pos = (input_ids[b] == vid_id).nonzero(as_tuple=False).squeeze(1)
                    if vid_pos.numel() > 0:
                        vid_pos = vid_pos[valid_mask[vid_pos]]

                    if vid_pos.numel() < patch_len or patch_len <= 0:
                        # No usable video region -> keep all valid tokens (drop padding)
                        keep_idx = torch.nonzero(valid_mask, as_tuple=False).squeeze(1)

                        new_embeds_list.append(inputs_embeds[b, keep_idx])
                        new_mask_list.append(attn2d[b, keep_idx])

                        if new_pos_list is not None:
                            if position_ids.dim() == 2:
                                new_pos_list.append(position_ids[b, keep_idx])
                            else:
                                new_pos_list.append(position_ids[keep_idx])

                        orig_video_counts.append(0)
                        kept_video_counts.append(0)
                        semantic_prune_coords_batch.append(None)
                        continue

                    patch_pos = vid_pos[:patch_len]
                    # Any remaining video tokens (e.g. trailing newline) are kept unconditionally

                    video_hs = inputs_embeds[b, patch_pos].view(T, P, D)
                    frame_global = video_hs.mean(dim=1)  # (T,D)
                    frame_scores = video_hs.float().norm(dim=-1)  # (T,P) saliency proxy

                    q_ids_b = None
                    q_mask_b = None
                    if query_ids is not None:
                        q_ids_b = query_ids[b] if query_ids.dim() == 2 else query_ids
                    if query_attention_mask is not None:
                        q_mask_b = query_attention_mask[b] if query_attention_mask.dim() == 2 else query_attention_mask

                    q_embed = self._compute_query_embedding(
                        input_ids=input_ids[b],
                        inputs_embeds=inputs_embeds[b],
                        attention_mask=attn2d[b],
                        query_ids=q_ids_b,
                        query_attention_mask=q_mask_b,
                    )

                    return_coords = bool(getattr(self, "semantic_return_coords", 0))
                    if return_coords:
                        _, keep_in_region, keep_coords = self._semantic_prune_video_region(
                            video_hidden_states=video_hs,
                            frame_token_scores=frame_scores,
                            frame_global_features=frame_global,
                            query_embed=q_embed,
                            device=device,
                            return_coords=True,
                        )
                        semantic_prune_coords_batch.append(keep_coords)
                    else:
                        _, keep_in_region = self._semantic_prune_video_region(
                            video_hidden_states=video_hs,
                            frame_token_scores=frame_scores,
                            frame_global_features=frame_global,
                            query_embed=q_embed,
                            device=device,
                            return_coords=False,
                        )
                        semantic_prune_coords_batch.append(None)

                    if keep_in_region.numel() == 0:
                        keep_in_region = torch.arange(patch_len, device=device, dtype=torch.long)

                    keep_in_region = keep_in_region.to(dtype=torch.long)
                    kept_patch_pos = patch_pos[keep_in_region]

                    # Keep all non-video tokens + kept video patch tokens
                    video_mask = torch.zeros((S0,), device=device, dtype=torch.bool)
                    video_mask[patch_pos] = True

                    keep_non_video = torch.nonzero(valid_mask & ~video_mask, as_tuple=False).squeeze(1)
                    keep_idx = torch.unique(torch.cat([keep_non_video, kept_patch_pos], dim=0)).sort().values

                    new_embeds_list.append(inputs_embeds[b, keep_idx])
                    new_mask_list.append(attn2d[b, keep_idx])

                    if new_pos_list is not None:
                        if position_ids.dim() == 2:
                            new_pos_list.append(position_ids[b, keep_idx])
                        else:
                            new_pos_list.append(position_ids[keep_idx])

                    orig_video_counts.append(patch_len)
                    kept_video_counts.append(int(kept_patch_pos.numel()))

                # Pad to the max length across batch
                Smax = max(x.shape[0] for x in new_embeds_list)
                padded_embeds = inputs_embeds.new_zeros((B, Smax, D))
                padded_mask = attn2d.new_zeros((B, Smax))
                padded_pos = None
                if new_pos_list is not None:
                    padded_pos = position_ids.new_zeros((B, Smax))

                for b in range(B):
                    Lb = new_embeds_list[b].shape[0]
                    padded_embeds[b, :Lb] = new_embeds_list[b]
                    padded_mask[b, :Lb] = new_mask_list[b]
                    if padded_pos is not None:
                        padded_pos[b, :Lb] = new_pos_list[b]

                inputs_embeds = padded_embeds
                attention_mask = padded_mask
                if padded_pos is not None:
                    position_ids = padded_pos

                # cache_position aligned to new length (keep 1D, safest)
                cache_position = torch.arange(Smax, device=device, dtype=torch.long)

                # ---- stats & logging ----
                kept_video_tokens_total = int(sum(kept_video_counts))
                orig_video_tokens_total = int(sum(orig_video_counts))

                kept_ratio_seq = float(Smax) / float(S0)
                kept_ratio_video = float(kept_video_tokens_total) / float(max(orig_video_tokens_total, 1))

                tflops_orig = float(self._tflops_video_tokens_batch(orig_video_counts))
                tflops_kept = float(self._tflops_video_tokens_batch(kept_video_counts))
                tflops_ratio = (tflops_kept / tflops_orig) if tflops_orig > 0 else 0.0

                self.fastvid_last_stats = {
                    "tflops_video_ratio": float(tflops_ratio * 100.0),
                    "kept_ratio_video": float(kept_ratio_video * 100.0),
                    "orig_tflops_video": float(tflops_orig),
                    "kept_tflops_video": float(tflops_kept),
                    "orig_video_tokens": int(orig_video_tokens_total),
                    "kept_video_tokens": int(kept_video_tokens_total),
                    "orig_seq_len": int(S0),
                    "new_seq_len": int(Smax),
                    "kept_ratio_seq": float(kept_ratio_seq * 100.0),
                }
                self.last_semantic_prune_coords = semantic_prune_coords_batch

                if (not torch.distributed.is_available()) or (not torch.distributed.is_initialized()) or torch.distributed.get_rank() == 0:
                    logger.info("[Metrics]" + json.dumps(self.fastvid_last_stats, ensure_ascii=False))

        outputs = self.language_model(
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            use_cache=use_cache,
            output_attentions=output_attentions,
            output_hidden_states=output_hidden_states,
            return_dict=True,
            cache_position=cache_position,
            **kwargs,
        )

        return LlavaOnevisionModelOutputWithPast(
            last_hidden_state=outputs.last_hidden_state,
            past_key_values=outputs.past_key_values,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions,
            image_hidden_states=image_features if pixel_values is not None else None,
            video_hidden_states=video_features if pixel_values_videos is not None else None,
        )

    def get_video_features(
        self,
        pixel_values: torch.FloatTensor,
        vision_feature_layer: Union[int, list[int]],
        vision_feature_select_strategy: str,
    ):
        """
        Obtains video last hidden states from the vision tower, apply multimodal projection and pooling.

        Args:
            pixel_values (`torch.FloatTensor]` of shape `(batch_size, num_frames, channels, height, width)`)
               The tensors corresponding to the input video.
            vision_feature_layer (`Union[int, list[int]], *optional*, defaults to -2`):
                The index of the layer to select the vision feature. If multiple indices are provided,
                the vision feature of the corresponding indices will be concatenated to form the
                vision features.
            vision_feature_select_strategy (`str`):
                The feature selection strategy used to select the vision feature from the vision backbone.
                Can be one of `"default"` or `"full"`
        Returns:
            video_features (list[`torch.Tensor`]): List of video feature tensor, each contains all the visual feature of all patches
            and are of shape `(num_videos, video_length, embed_dim)`).
        """
        batch_size, frames, channels, height, width = pixel_values.shape
        pixel_values = pixel_values.view(batch_size * frames, channels, height, width)
        video_features = self.vision_tower(pixel_values, output_hidden_states=True)

        # If we have one vision feature layer, return the corresponding hidden states,
        # otherwise, select the hidden states of each feature layer and concatenate them
        if isinstance(vision_feature_layer, int):
            selected_video_feature = video_features.hidden_states[vision_feature_layer]
        else:
            hs_pool = [video_features.hidden_states[layer_idx] for layer_idx in vision_feature_layer]
            selected_video_feature = torch.cat(hs_pool, dim=-1)

        if vision_feature_select_strategy == "default":
            selected_video_feature = selected_video_feature[:, 1:]
        video_features = self.multi_modal_projector(selected_video_feature)

        video_features = self.apply_pooling(video_features)
        video_features = video_features.reshape(batch_size, frames * video_features.shape[1], -1)

        return video_features

    def apply_pooling(self, image_features):
        height = width = self.config.vision_config.image_size // self.config.vision_config.patch_size
        batch_frames, seq_len, dim = image_features.shape
        image_features = image_features.view(batch_frames, height, width, -1)
        image_features = image_features.permute(0, 3, 1, 2).contiguous()

        height, width = image_features.shape[2:]
        scaled_shape = [math.ceil(height / 2), math.ceil(width / 2)]
        image_features = nn.functional.interpolate(image_features, size=scaled_shape, mode="bilinear")

        image_features = image_features.permute(0, 2, 3, 1)
        image_features = image_features.view(batch_frames, -1, dim)
        return image_features

    # ======================================================================
    # SemVID: Semantic-oriented pruning (Query-aware + Coherence + Diversity)
    # ======================================================================

    def _compute_query_embedding(
            self,
            *,
            input_ids: torch.LongTensor,  # (S,) 当前 sample 的 input_ids
            inputs_embeds: torch.FloatTensor,  # (S,D) 当前 sample 的 inputs_embeds（已经 scatter 过视频/图像）
            attention_mask: Optional[torch.Tensor] = None,  # (S,) 2D mask 的一行
            query_ids: Optional[torch.LongTensor] = None,  # (L,) 纯 query ids（可选）
            query_attention_mask: Optional[torch.Tensor] = None,  # (L,) 可选
    ) -> torch.FloatTensor:
        """Compute a lightweight query/text embedding (no extra decoder forward).

        Engineering note
        ---------------
        Qwen3VL is a *decoder-only* multimodal model (visual embeddings are scattered into the token
        sequence and then processed by self-attention). There is no standalone "text->vision cross-attn"
        module that we can cheaply query *before* decoding. Therefore, if we want Stage-1 (query-conditioned
        temporal proposal) to be truly lightweight, we should avoid using decoder attentions.

        This helper mean-pools **text token embeddings** (embedding-layer outputs) as a cheap query prior.
        We exclude:
          - image/video placeholder tokens
          - vision span markers (vision_start/vision_end)
          - padding positions (attention_mask == 0)

        Returns:
            q: (hidden_dim,) L2-normalized.
        """
        # ---------- 1) choose source ids/mask + get token embeddings ----------
        use_query = (query_ids is not None) and (query_ids.numel() > 0)

        if use_query:
            ids = query_ids
            mask = query_attention_mask
            tok_embeds = self.get_input_embeddings()(ids)  # (L,D)
        else:
            ids = input_ids
            mask = attention_mask
            tok_embeds = inputs_embeds  # (S,D)

        # ---------- 2) build validity mask ----------
        if mask is None:
            # 没给 mask 时，用 pad_token_id 做个粗过滤
            pad_id = getattr(self.config, "pad_token_id", None)
            if pad_id is not None:
                valid = ids.ne(pad_id)
            else:
                valid = torch.ones_like(ids, dtype=torch.bool)
        else:
            valid = mask.to(dtype=torch.bool)

        for attr in ["bos_token_id", "eos_token_id", "image_token_id", "video_token_id", "vision_start_token_id",
                     "vision_end_token_id"]:
            tid = getattr(self.config, attr, None)
            if tid is not None:
                valid = valid & ids.ne(tid)

        if valid.sum().item() == 0:
            valid = torch.ones_like(ids, dtype=torch.bool)

        # ---------- 3) (multi-token) or mean pooling ----------
        tok_valid = tok_embeds[valid]  # (L,D)

        if tok_valid.shape[0] == 0:
            tok_valid = tok_embeds[:1]

        # If query is short: return per-token embeddings (row-wise normalized)
        if tok_valid.shape[0] <= self.semantic_query_token_max:
            q_tok = tok_valid / tok_valid.norm(dim=-1, keepdim=True).clamp_min(1e-6)  # (L,D)
            return q_tok

        # Otherwise: mean-pool for efficiency
        q = tok_valid.mean(dim=0)  # (D,)
        q = q / q.norm(dim=-1).clamp_min(1e-6)
        return q

    def _allocate_integer_budget(self, weights: torch.Tensor, total: int) -> torch.LongTensor:
        """Allocate an integer budget according to non-negative weights.

        Args:
            weights: (N,) float tensor.
            total: int, >=0

        Returns:
            alloc: (N,) long tensor, alloc.sum() == total
        """
        if total <= 0:
            return torch.zeros_like(weights, dtype=torch.long)

        if weights.numel() == 0:
            return torch.empty((0,), device=weights.device, dtype=torch.long)

        w = weights.float().clamp_min(0)
        if w.sum() < 1e-8:
            w = torch.ones_like(w)

        raw = w / w.sum() * float(total)
        flo = torch.floor(raw).to(torch.long)
        rem = int(total - flo.sum().item())
        if rem > 0:
            frac = (raw - flo.float())
            top = torch.topk(frac, k=min(rem, frac.numel())).indices
            flo[top] += 1
        return flo

    def _allocate_integer_budget_with_cap(
            self,
            weights: torch.Tensor,
            total: int,
            cap: torch.LongTensor,
    ) -> torch.LongTensor:
        """Allocate integer budget with an upper-bound per bin (cap).

        This is used to (re-)distribute leftover budget without overflowing per-frame capacity (<=P).

        Args:
            weights: (N,) float tensor.
            total: int, >=0
            cap: (N,) long tensor, cap[i] >= 0

        Returns:
            alloc: (N,) long tensor, 0<=alloc[i]<=cap[i], alloc.sum()==min(total, cap.sum()).
        """
        if total <= 0 or weights.numel() == 0:
            return torch.zeros_like(cap, dtype=torch.long)

        device = weights.device
        cap = cap.to(device)
        total = int(min(total, int(cap.sum().item())))
        if total <= 0:
            return torch.zeros_like(cap, dtype=torch.long)

        alloc = torch.zeros_like(cap, dtype=torch.long)
        active = cap > 0

        # Work in rounds: allocate budget among active bins, then clamp to remaining cap, repeat if overflow.
        remaining = total
        for _ in range(16):  # hard cap iterations for safety
            if remaining <= 0 or not bool(active.any()):
                break

            w = weights.float().clamp_min(0)
            w = w * active.float()
            if w.sum() < 1e-8:
                # If all weights are ~0, fallback to uniform over active bins.
                w = active.float()

            raw = w / w.sum() * float(remaining)
            flo = torch.floor(raw).to(torch.long)
            rem = int(remaining - flo.sum().item())
            if rem > 0:
                frac = (raw - flo.float())
                frac = frac.masked_fill(~active, -1.0)
                top = torch.topk(frac, k=min(rem, int(active.sum().item()))).indices
                flo[top] += 1

            # Clamp to remaining cap
            remaining_cap = cap - alloc
            flo = torch.minimum(flo, remaining_cap)

            used = int(flo.sum().item())
            alloc = alloc + flo
            remaining -= used

            # Update active
            active = (cap - alloc) > 0

            # If we couldn't use any budget in this round, stop to avoid infinite loops.
            if used == 0:
                break

        return alloc

    def _mmr_select(
            self,
            rel_scores: torch.Tensor,  # (Nc,)
            cand_embeds_norm: torch.Tensor,  # (Nc, D), already L2-normalized
            k: int,
            lambda_mmr: float,
    ) -> torch.LongTensor:
        """MMR (Maximal Marginal Relevance) selection for diversity.

        This returns indices in [0, Nc) that balance relevance and diversity:
            argmax  lambda*rel - (1-lambda)*max_sim_to_selected

        Complexity: O(k*Nc), suitable for per-frame small-k selection.

        Returns:
            selected: (<=k,) long tensor of indices into candidates.
        """
        Nc = int(rel_scores.numel())
        if k <= 0 or Nc <= 0:
            return rel_scores.new_empty((0,), dtype=torch.long)

        k = min(int(k), Nc)
        lambda_mmr = float(lambda_mmr)

        # pick the most relevant first
        first = int(torch.argmax(rel_scores).item())
        selected = [first]
        if k == 1:
            return torch.tensor(selected, device=rel_scores.device, dtype=torch.long)

        available = torch.ones(Nc, device=rel_scores.device, dtype=torch.bool)
        available[first] = False

        # redundancy score: max cosine similarity to selected set
        redundancy = torch.matmul(cand_embeds_norm, cand_embeds_norm[first].unsqueeze(-1)).squeeze(-1)

        for _ in range(k - 1):
            if not bool(available.any()):
                break

            mmr = lambda_mmr * rel_scores - (1.0 - lambda_mmr) * redundancy
            mmr = mmr.masked_fill(~available, -1e9)

            nxt = int(torch.argmax(mmr).item())
            selected.append(nxt)
            available[nxt] = False

            sim_n = torch.matmul(cand_embeds_norm, cand_embeds_norm[nxt].unsqueeze(-1)).squeeze(-1)
            redundancy = torch.maximum(redundancy, sim_n)

        return torch.tensor(selected, device=rel_scores.device, dtype=torch.long)

    def _semantic_prune_video_region(
            self,
            video_hidden_states: torch.FloatTensor,  # (T, P, D)
            frame_token_scores: Optional[torch.FloatTensor],  # (T, P) token saliency proxy (vision output norm)
            frame_global_features: torch.FloatTensor,  # (T, D) mean feature per frame
            query_embed: torch.FloatTensor,  # (D,)
            device: torch.device,
            return_coords: bool = False,
    ):
        """Semantic-oriented pruning for a *single* video's token region.

        Stage-1 (Query-conditioned temporal proposal, lightweight)
        ---------------------------------------------------------
        1) Compute per-frame relevance: cosine(query_embed, frame_global_feature)
        2) Smooth relevance to reduce noise
        3) Use DySeg (query-agnostic) to split into continuous segments (scene boundaries)
        4) Allocate an *extra* token budget to top-k segments (continuous blocks), based on segment relevance.
           Frames outside those blocks still keep >=min_tokens_per_frame tokens to preserve coherence.

        Stage-2 (Within-segment semantic pruning, structured)
        ----------------------------------------------------
        For each frame:
          - Scene/context tokens (query-agnostic): keep proto scene tokens to guarantee continuity
          - Object tokens (query-aware): select with MMR for diversity
          - Motion tokens: select tokens with large temporal differences

        Returns:
            pruned_video_tokens: (N_keep, D) kept token embeddings (not mandatory for the outer logic)
            keep_in_video_region: (N_keep,) indices in [0, T*P)
        """
        # Shapes
        T, P, D = video_hidden_states.shape
        if T <= 0 or P <= 0:
            raise ValueError(f"Invalid video_hidden_states shape: {tuple(video_hidden_states.shape)}")

        # ---- 0) Normalize query + frame globals ----
        fg = frame_global_features.to(device)
        fg_norm = fg / fg.norm(dim=-1, keepdim=True).clamp_min(1e-6)

        q_in = query_embed.to(device)
        q_tokens = None  # (L,D) if provided
        q_vec = None  # (D,) pooled fallback / compatibility
        if q_in.ndim == 1:
            if q_in.shape[0] == D:
                q_vec = q_in
            else:
                q_vec = fg_norm.mean(dim=0)
        elif q_in.ndim == 2:
            if (q_in.shape[0] > 0) and (q_in.shape[1] == D):
                q_tokens = q_in / q_in.norm(dim=-1, keepdim=True).clamp_min(1e-6)  # (L,D)
                q_vec = q_tokens.mean(dim=0)
            else:
                q_vec = fg_norm.mean(dim=0)
        else:
            q_vec = fg_norm.mean(dim=0)

        q_vec = q_vec / q_vec.norm(dim=-1).clamp_min(1e-6)

        # frame relevance prior (single or multi-token)
        if q_tokens is None:
            frame_rel = (fg_norm * q_vec.unsqueeze(0)).sum(dim=-1)  # (T,)
        else:
            rel_mat = torch.matmul(fg_norm, q_tokens.t())  # (T,L)
            if rel_mat.shape[1] == 1:
                frame_rel = rel_mat.squeeze(1)
            else:
                # more stable than pure max
                k_red = min(2, rel_mat.shape[1])
                frame_rel = torch.topk(rel_mat, k=k_red, dim=1).values.mean(dim=1)  # (T,)

        # optional smoothing (replicate padding)
        frame_rel_s = frame_rel
        win = self.semantic_stage1_smooth_win
        if win > 1 and T >= 3:
            if win % 2 == 0:
                win += 1
            # keep odd window <= T
            win = min(win, T if (T % 2 == 1) else max(T - 1, 1))
            if win >= 3:
                x = frame_rel.view(1, 1, T)
                pad = win // 2
                x = torch.nn.functional.pad(x, (pad, pad), mode="replicate")
                kernel = torch.ones((1, 1, win), device=device, dtype=x.dtype) / float(win)
                frame_rel_s = torch.nn.functional.conv1d(x, kernel).view(-1)

        # ---- 1) DySeg split into continuous segments (query-agnostic) ----
        if T <= 1:
            seg_sizes = [T]
        else:
            adj_sim = (fg_norm[:-1] * fg_norm[1:]).sum(dim=-1)  # (T-1,)
            k = max(int(self.fastvid_DySeg_c) - 1, 0)
            k = min(k, int(adj_sim.numel()))
            cut_topk = torch.topk(adj_sim, k, largest=False).indices if k > 0 else adj_sim.new_empty((0,),
                                                                                                     dtype=torch.long)
            cut_tau = torch.nonzero(adj_sim < float(self.fastvid_DySeg_tau)).squeeze(1)
            cut = torch.unique(torch.cat([cut_topk, cut_tau])).sort().values

            if cut.numel() == 0:
                seg_sizes = [T]
            else:
                seg_sizes = [int(cut[0].item()) + 1]
                for i in range(1, cut.numel()):
                    seg_sizes.append(int(cut[i].item() - cut[i - 1].item()))
                seg_sizes.append(int(T - cut[-1].item() - 1))
                seg_sizes = [s for s in seg_sizes if s > 0]
                if len(seg_sizes) == 0:
                    seg_sizes = [T]

        # ---- 2) Allocate token budget across segments/frames (coherence safe) ----
        base_k = self.semantic_min_tokens_per_frame
        base_k = max(min(base_k, P), 1)
        ratio = self.semantic_retention_ratio
        ratio = max(min(ratio, 1.0), 0.0)

        total_tokens = int(T * P)
        target_keep = int(round(total_tokens * ratio))
        target_keep = max(target_keep, int(T * base_k))
        target_keep = min(target_keep, total_tokens)
        if self.ablation_uniform_allocation:
            base_k = 0
            # Uniform per-frame allocation (as even as possible):
            # - every frame gets k_floor tokens
            # - distribute the remainder (+1) to evenly spaced frames
            k_floor = int(target_keep // T)
            remainder = int(target_keep - k_floor * T)

            frame_keep = torch.full((T,), k_floor, device=device, dtype=torch.long)
            if remainder > 0:
                # Deterministic, roughly evenly spaced indices in [0, T)
                idx = (torch.arange(remainder, device=device) * T // remainder).long()
                frame_keep[idx] += 1

            # (optional safety; should already hold)
            frame_keep = torch.clamp(frame_keep, min=base_k, max=P)
        else:
            # Segment ranges + scores
            seg_starts = []
            seg_scores = []
            st = 0
            for sz in seg_sizes:
                ed = st + sz
                seg_starts.append(st)
                seg_scores.append(frame_rel_s[st:ed].mean())
                st = ed
            seg_scores = torch.stack(seg_scores, dim=0)  # (Nseg,)

            ### Context Tokens: minimum tokens per frame to preserve coherence

            remaining = int(target_keep - T * base_k)

            # segment budget allocation: top-k blocks get extra budget by query relevance; others keep only base_k per frame
            w_seg = torch.relu(seg_scores)
            if w_seg.sum() < 1e-8:
                w_seg = (seg_scores - seg_scores.min()).clamp_min(0) + 1e-6

            topk = self.semantic_stage1_topk_segments
            if topk > 0 and topk < int(w_seg.numel()):
                top_idx = torch.topk(w_seg, k=topk).indices
                w_mask = torch.zeros_like(w_seg)
                w_mask[top_idx] = w_seg[top_idx]
                w_seg = w_mask
                # If all zero after masking, make them uniform on selected segments
                if w_seg.sum() < 1e-8:
                    w_seg[top_idx] = 1.0

            # per-frame motion energy for allocation (cheap: based on frame-global diffs)
            motion_energy = torch.zeros((T,), device=device, dtype=frame_rel_s.dtype)
            if T > 1:
                diff = fg_norm[1:] - fg_norm[:-1]
                motion_energy[1:] = diff.norm(dim=-1)
                motion_energy[0] = motion_energy[1]

            frame_keep = torch.full((T,), base_k, device=device, dtype=torch.long)

            if remaining > 0:
                seg_extra = self._allocate_integer_budget(w_seg, remaining)  # (Nseg,)

                # frame budget allocation: distribute segment budget to frames inside the segment
                alpha = self.semantic_frame_weight_alpha
                st = 0
                for i, sz in enumerate(seg_sizes):
                    ed = st + sz
                    extra_i = int(seg_extra[i].item())
                    if extra_i > 0:
                        sim_w = torch.relu(frame_rel_s[st:ed])
                        mot_w = motion_energy[st:ed].clamp_min(0)
                        w_frm = alpha * sim_w + (1.0 - alpha) * mot_w
                        if w_frm.sum() < 1e-8:
                            w_frm = torch.ones_like(w_frm)

                        frame_extra = self._allocate_integer_budget(w_frm, extra_i)
                        frame_keep[st:ed] += frame_extra
                    st = ed

                # Clamp to per-frame max P, then re-distribute if rounding/clamping caused deficit
                frame_keep = torch.clamp(frame_keep, max=P)
                cur_sum = int(frame_keep.sum().item())
                if cur_sum < target_keep:
                    leftover = int(target_keep - cur_sum)
                    slack = (P - frame_keep).clamp_min(0)
                    if int(slack.sum().item()) > 0 and leftover > 0:
                        sim_all = torch.relu(frame_rel_s)
                        mot_all = motion_energy.clamp_min(0)
                        w_all = alpha * sim_all + (1.0 - alpha) * mot_all

                        # Respect slack: bins with slack=0 should never receive budget
                        w_all = w_all * slack.float()
                        if w_all.sum() < 1e-8:
                            w_all = slack.float()

                        add = self._allocate_integer_budget_with_cap(w_all, leftover, slack)
                        frame_keep = frame_keep + add

        # ---- 3) Within-frame structured token selection ----
        selector = self.ablation_use_semantic_selection

        if selector == "fastvid":
            # frame_token_scores 在你们调用点传的是 frame_attn_weights_per_sample[b] :contentReference[oaicite:8]{index=8}
            frame_aw = frame_token_scores
            if frame_aw is None:
                frame_aw = video_hidden_states.float().norm(dim=-1)  # (T,P) fallback

            keep_in_video_region = self._fastvid_select_keep_indices_with_budget(
                video_hidden_states=video_hidden_states,
                frame_attn_weights=frame_aw.to(device),
                frame_keep=frame_keep,
                seg_sizes=seg_sizes,
                device=device,
            )

            pruned_video_tokens = video_hidden_states.reshape(T * P, D)[keep_in_video_region]
            return pruned_video_tokens, keep_in_video_region

        # Score fallback if not provided
        if frame_token_scores is None:
            frame_token_scores = video_hidden_states.float().norm(dim=-1)
        frame_token_scores = frame_token_scores.to(device)

        # Pre-compute token motion scores (token-wise temporal difference)
        # We'll compute per-frame on demand to avoid storing a large (T,P) tensor when not needed.
        obj_ratio = self.semantic_obj_ratio
        lambda_mmr = self.semantic_mmr_lambda

        keep_local_indices = []
        ctx_pairs_list: List[torch.LongTensor] = []
        obj_pairs_list: List[torch.LongTensor] = []
        mot_pairs_list: List[torch.LongTensor] = []
        for t in range(T):
            k_total = int(frame_keep[t].item())
            if k_total <= 0:
                continue
            k_total = min(k_total, P)

            tokens = video_hidden_states[t].to(device)  # (P,D)
            scores = frame_token_scores[t]  # (P,)

            # Normalize tokens for cosine similarity
            tok_norm = tokens / tokens.norm(dim=-1, keepdim=True).clamp_min(1e-6)

            sim_tok_q = None
            if q_tokens is not None:
                # (P,L) cosine sim between each video token and each query token
                sim_tok_q = torch.matmul(tok_norm, q_tokens.t())

            # ---- Scene/context tokens (query-agnostic) ----
            # Choose a proto token closest to the frame-global mean (helps preserve background context).
            mean_norm = fg_norm[t]  # already normalized
            proto = int(torch.argmax(torch.matmul(tok_norm, mean_norm)).item())

            sel_mask = torch.zeros((P,), device=device, dtype=torch.bool)
            sel_mask[proto] = True
            sel_mask = torch.zeros((P,), device=device, dtype=torch.bool)
            ctx_mask = torch.zeros((P,), device=device, dtype=torch.bool)
            obj_mask = torch.zeros((P,), device=device, dtype=torch.bool)
            mot_mask = torch.zeros((P,), device=device, dtype=torch.bool)
            sel_mask[proto] = True
            ctx_mask[proto] = True

            # If base_k > 1, add more scene/context tokens using token saliency (norm proxy), avoiding duplicates.
            if base_k > 1:
                # Mask out already selected proto
                sc = scores.clone()
                sc[sel_mask] = -1e9
                k_ctx = min(int(base_k - 1), int((~sel_mask).sum().item()))
                if k_ctx > 0:
                    ctx_idx = torch.topk(sc, k=k_ctx).indices
                    sel_mask[ctx_idx] = True
                    ctx_mask[ctx_idx] = True

            # Remaining budget in this frame
            extra = int(k_total - int(sel_mask.sum().item()))
            if extra > 0:
                k_obj = int(round(extra * obj_ratio))
                k_obj = max(min(k_obj, extra), 0)
                k_mot = extra - k_obj

                # ---- Object tokens (query-aware) with diversity via MMR ----
                if k_obj > 0:
                    cand_idx = torch.arange(P, device=device)[~sel_mask]
                    if cand_idx.numel() > 0:
                        # --- single-vector query (old behavior) ---
                        if q_tokens is None:
                            cand_emb = tok_norm[cand_idx]
                            rel = torch.matmul(cand_emb, q_vec)  # (Nc,)
                            sel_rel = self._mmr_select(rel_scores=rel, cand_embeds_norm=cand_emb, k=k_obj,
                                                       lambda_mmr=lambda_mmr)
                            if sel_rel.numel() > 0:
                                sel_mask[cand_idx[sel_rel]] = True
                                obj_mask[cand_idx[sel_rel]] = True
                        # --- multi-token query (coverage-aware) ---
                        else:
                            # Allocate k_obj across query tokens based on their "presence" in this frame.
                            # Use max similarity per query token within this frame as weights.
                            w_q = sim_tok_q.max(dim=0).values.clamp_min(0)  # (L,)
                            alloc_q = self._allocate_integer_budget(w_q, k_obj)  # (L,)
                            # Handle more "present" query tokens first (greedy improves stability)
                            order = torch.argsort(w_q, descending=True)

                            for qi in order.tolist():
                                ki = int(alloc_q[qi].item())
                                if ki <= 0:
                                    continue
                                cand_idx2 = torch.arange(P, device=device)[~sel_mask]
                                if cand_idx2.numel() == 0:
                                    break
                                cand_emb2 = tok_norm[cand_idx2]
                                rel2 = sim_tok_q[cand_idx2, qi]  # (Nc2,)
                                sel_rel2 = self._mmr_select(rel_scores=rel2, cand_embeds_norm=cand_emb2, k=ki,
                                                            lambda_mmr=lambda_mmr)
                                if sel_rel2.numel() > 0:
                                    sel_mask[cand_idx2[sel_rel2]] = True
                                    obj_mask[cand_idx2[sel_rel2]] = True

                # ---- Motion tokens (query-agnostic, action sensitive) ----
                if k_mot > 0:
                    cand_idx = torch.arange(P, device=device)[~sel_mask]
                    if cand_idx.numel() > 0:
                        if T == 1:
                            mot_score = torch.zeros((P,), device=device, dtype=tokens.dtype)
                        elif t == 0:
                            mot_score = (video_hidden_states[1].to(device) - video_hidden_states[0].to(
                                device)).float().norm(dim=-1)
                        elif t == T - 1:
                            mot_score = (video_hidden_states[t].to(device) - video_hidden_states[t - 1].to(
                                device)).float().norm(dim=-1)
                        else:
                            mot1 = (video_hidden_states[t].to(device) - video_hidden_states[t - 1].to(
                                device)).float().norm(dim=-1)
                            mot2 = (video_hidden_states[t + 1].to(device) - video_hidden_states[t].to(
                                device)).float().norm(dim=-1)
                            mot_score = 0.5 * (mot1 + mot2)

                        ms = mot_score[cand_idx].float()
                        # Optional: make motion selection query-aware when multi-token query is available
                        beta_m = self.semantic_motion_query_beta
                        if (q_tokens is not None) and (beta_m > 1e-6) and (sim_tok_q is not None):
                            mot_n = ms / ms.max().clamp_min(1e-6)
                            sim_any = sim_tok_q[cand_idx].max(dim=1).values  # (Nc,)
                            sim_pos = sim_any.clamp_min(0)
                            sim_n = sim_pos / sim_pos.max().clamp_min(1e-6)
                            ms = (1.0 - beta_m) * mot_n + beta_m * sim_n
                        k_mot = min(k_mot, int(cand_idx.numel()))
                        if k_mot > 0:
                            topm = torch.topk(ms, k=k_mot).indices
                            sel_mask[cand_idx[topm]] = True
                            mot_mask[cand_idx[topm]] = True

                # ---- Fill (if still deficit) with saliency ----
                cur_cnt = int(sel_mask.sum().item())
                if cur_cnt < k_total:
                    need = int(k_total - cur_cnt)
                    cand_idx = torch.arange(P, device=device)[~sel_mask]
                    if cand_idx.numel() > 0:
                        k_fill = min(need, int(cand_idx.numel()))
                        topf = torch.topk(scores[cand_idx], k=k_fill).indices
                        sel_mask[cand_idx[topf]] = True
                        ctx_mask[cand_idx[topf]] = True

            # Guard: never let a frame become empty
            if int(sel_mask.sum().item()) == 0:
                sel_mask[0] = True
                ctx_mask[0] = True

            sel_local = torch.nonzero(sel_mask, as_tuple=False).squeeze(1).sort().values  # ascending
            keep_local_indices.append(sel_local + t * P)
            if return_coords:
                if bool(ctx_mask.any()):
                    c = torch.nonzero(ctx_mask, as_tuple=False).squeeze(1).to(torch.long)
                    if c.numel() > 0:
                        ctx_pairs_list.append(torch.stack([torch.full_like(c, t), c], dim=1))
                if bool(obj_mask.any()):
                    o = torch.nonzero(obj_mask, as_tuple=False).squeeze(1).to(torch.long)
                    if o.numel() > 0:
                        obj_pairs_list.append(torch.stack([torch.full_like(o, t), o], dim=1))
                if bool(mot_mask.any()):
                    m_ = torch.nonzero(mot_mask, as_tuple=False).squeeze(1).to(torch.long)
                    if m_.numel() > 0:
                        mot_pairs_list.append(torch.stack([torch.full_like(m_, t), m_], dim=1))

        if len(keep_local_indices) == 0:
            keep_in_video_region = torch.arange(T * P, device=device, dtype=torch.long)
        else:
            keep_in_video_region = torch.cat(keep_local_indices, dim=0).sort().values

        pruned_video_tokens = video_hidden_states.reshape(T * P, D).to(device)[keep_in_video_region]
        if not return_coords:
            return pruned_video_tokens, keep_in_video_region

        empty = torch.empty((0, 2), device=device, dtype=torch.long)
        ctx_pairs = torch.cat(ctx_pairs_list, dim=0) if len(ctx_pairs_list) > 0 else empty
        obj_pairs = torch.cat(obj_pairs_list, dim=0) if len(obj_pairs_list) > 0 else empty
        mot_pairs = torch.cat(mot_pairs_list, dim=0) if len(mot_pairs_list) > 0 else empty

        def _sort_pairs(pairs: torch.LongTensor) -> torch.LongTensor:
            if pairs.numel() == 0:
                return pairs

            gid = pairs[:, 0] * P + pairs[:, 1]
            order = torch.argsort(gid)
            return pairs[order]

        keep_coords = {
            "context": _sort_pairs(ctx_pairs),
            "object": _sort_pairs(obj_pairs),
            "motion": _sort_pairs(mot_pairs),
        }
        return pruned_video_tokens, keep_in_video_region, keep_coords

    def _fastvid_select_keep_indices_with_budget(
            self,
            video_hidden_states: torch.Tensor,  # (T, P, D)
            frame_attn_weights: torch.Tensor,  # (T, P)  (你们的 frame_token_scores 就是这个)
            frame_keep: torch.Tensor,  # (T,)
            seg_sizes: list,  # DySeg 的段长度列表（可直接复用你们已有的 seg_sizes）
            *,
            device: torch.device,
    ) -> torch.Tensor:
        """
        Return keep indices into flattened (T*P) tokens.
        Salient: top-k by attention weights.
        Context: density-peak sampling on remaining tokens (FastVID).
        """

        T, P, D = video_hidden_states.shape
        d = float(getattr(self, "fastvid_STPrune_d", 0.25))  # FastVID 的 salient/context 比例
        p = int(getattr(self, "fastvid_DTM_p", 4))  # FastVID 的 grouping stride（仅用于决定哪些帧产 context）
        p = max(p, 1)

        keep = []
        frame_base = 0  # frame offset

        for sz in seg_sizes:
            segF = int(sz)
            if segF <= 0:
                continue

            seg_hs = video_hidden_states[frame_base:frame_base + segF]  # (segF,P,D)
            seg_aw = frame_attn_weights[frame_base:frame_base + segF]  # (segF,P)
            seg_fk = frame_keep[frame_base:frame_base + segF]  # (segF,)

            # FastVID 原版是从后往前每 p 帧产一组 context（减少 context 数，避免太慢）
            host_frames = set(range(segF - 1, -1, -p))  # segF-1, segF-1-p, ...

            for f in range(segF):
                k_total = int(seg_fk[f].item())
                k_total = max(min(k_total, P), 1)

                # 只有 host frame 分一部分 budget 给 context；其他帧全当 salient
                if f in host_frames:
                    c_k = int(round(k_total * d))
                    c_k = max(c_k, 1)
                    c_k = min(c_k, k_total, P // 2)
                else:
                    c_k = 0

                s_k = k_total - c_k  # salient count

                aw = seg_aw[f]  # (P,)
                if s_k > 0:
                    salient = torch.topk(aw, k=s_k, largest=True).indices.to(torch.long)
                else:
                    salient = torch.empty((0,), device=device, dtype=torch.long)

                if c_k > 0:
                    all_idx = torch.arange(P, device=device, dtype=torch.long)
                    mask = torch.zeros((P,), device=device, dtype=torch.bool)
                    if salient.numel() > 0:
                        mask[salient] = True
                    remain = all_idx[~mask]  # (Nr,)

                    # FastVID density-peak sampling on remaining tokens
                    tmp = seg_hs[f].index_select(0, remain).unsqueeze(0)  # (1,Nr,D)
                    Nr2 = tmp.shape[1]
                    Dd = tmp.shape[-1]

                    if Nr2 == 1:
                        sampled = torch.zeros((1, 1), device=device, dtype=torch.long)
                    else:
                        dist = torch.cdist(tmp.float(), tmp.float()) / (Dd ** 0.5)  # (1,Nr,Nr)
                        kn = min(4, Nr2)
                        dist_nearest, _ = torch.topk(dist, k=kn, dim=-1, largest=False)  # (1,Nr,kn)
                        density = (-(dist_nearest ** 2).mean(dim=-1)).exp()  # (1,Nr)
                        density = density + torch.rand_like(density) * 1e-6  # tie-break

                        m = (density[:, None, :] > density[:, :, None]).to(tmp.dtype)  # (1,Nr,Nr)
                        dist_max = dist.flatten(1).max(dim=-1)[0][:, None, None]  # (1,1,1)
                        dmin, _ = (dist * m + dist_max * (1 - m)).min(dim=-1)  # (1,Nr)

                        score = dmin * density  # (1,Nr)
                        _, sampled = torch.topk(score, k=c_k, dim=-1)  # (1,c_k)

                    ctx = remain[sampled.view(-1)].sort()[0].to(torch.long)  # (c_k,)
                else:
                    ctx = torch.empty((0,), device=device, dtype=torch.long)

                keep_frame = torch.cat([salient, ctx], dim=0)[:k_total]  # (k_total,)
                keep.append(keep_frame + (frame_base + f) * P)

            frame_base += segF

        keep_idx = torch.cat(keep, dim=0)
        keep_idx, _ = torch.sort(keep_idx)
        return keep_idx

    def _get_llm_flops_params(self):
        # 优先从 language_model.config 拿（更准确）
        cfg = getattr(getattr(self, "language_model", None), "config", None)
        if cfg is None:
            cfg = getattr(self.config, "text_config", None)
        if cfg is None:
            raise ValueError("Cannot find language model config for FLOPs calculation.")

        # L: layers
        L = getattr(cfg, "num_hidden_layers", None) or getattr(cfg, "n_layer", None)
        # D: hidden size
        Dm = getattr(cfg, "hidden_size", None) or getattr(cfg, "n_embd", None)
        # D': ffn intermediate
        Dff = getattr(cfg, "intermediate_size", None) or getattr(cfg, "ffn_hidden_size", None)

        # hkv: num_key_value_heads (GQA)
        hkv = getattr(cfg, "num_key_value_heads", None)
        if hkv is None:
            # 有些 config 叫 num_kv_heads
            hkv = getattr(cfg, "num_kv_heads", None)
        if hkv is None:
            # 没有 GQA 字段就退化为普通 MHA
            hkv = getattr(cfg, "num_attention_heads", None)

        # d: head_dim
        d = getattr(cfg, "head_dim", None)
        if d is None:
            # 常见：head_dim = hidden_size / num_attention_heads
            hq = getattr(cfg, "num_attention_heads", None)
            if hq is None:
                raise ValueError("Cannot infer head_dim: missing head_dim and num_attention_heads.")
            d = Dm // hq

        missing = [k for k, v in [("L", L), ("D", Dm), ("Dff", Dff), ("hkv", hkv), ("d", d)] if v is None]
        if missing:
            raise ValueError(f"Missing FLOPs params in config: {missing}")

        return int(L), int(Dm), int(Dff), int(hkv), int(d)

    def _tflops_video_tokens_batch(self, n_list):
        # 按 FastVID 附录式(6)：per-layer FLOPs
        # 2nD(hkv d) + 2nD^2 + 2n^2 D + 3nDD'
        L, Dm, Dff, hkv, d = self._get_llm_flops_params()

        total_flops = 0
        for n in n_list:
            n = int(n)
            per_layer = (
                    2 * n * Dm * (hkv * d)
                    + 2 * n * (Dm ** 2)
                    + 2 * (n ** 2) * Dm
                    + 3 * n * Dm * Dff
            )
            total_flops += L * per_layer

        return total_flops / 1e12  # TFLOPs

@auto_docstring(
    custom_intro="""
    The LLAVA-NeXT model which consists of a vision backbone and a language model.
    """
)
class LlavaOnevisionForConditionalGeneration(LlavaOnevisionPreTrainedModel, GenerationMixin):
    _checkpoint_conversion_mapping = {
        "^language_model.model": "model.language_model",
        "^vision_tower": "model.vision_tower",
        "^multi_modal_projector": "model.multi_modal_projector",
        "^image_newline": "model.image_newline",
        "^language_model.lm_head": "lm_head",
    }
    _tied_weights_keys = ["lm_head.weight"]

    def __init__(self, config: LlavaOnevisionConfig):
        super().__init__(config)
        self.model = LlavaOnevisionModel(config)
        self.lm_head = nn.Linear(config.text_config.hidden_size, config.text_config.vocab_size, bias=False)
        self.post_init()

        # Runtime metrics (synced from self.model in forward)
        self.fastvid_last_stats = {}
        self.last_semantic_prune_coords = None

    def get_input_embeddings(self):
        return self.model.get_input_embeddings()

    def set_input_embeddings(self, value):
        self.model.set_input_embeddings(value)

    def get_output_embeddings(self) -> nn.Module:
        return self.lm_head

    def set_decoder(self, decoder):
        self.model.set_decoder(decoder)

    def get_decoder(self):
        return self.model.get_decoder()

    def pack_image_features(self, image_features, image_sizes, vision_feature_select_strategy, image_newline=None):
        return self.model.pack_image_features(
            image_features=image_features,
            image_sizes=image_sizes,
            vision_feature_select_strategy=vision_feature_select_strategy,
            image_newline=image_newline,
        )

    def get_image_features(
        self,
        pixel_values: torch.FloatTensor,
        image_sizes: torch.Tensor,
        vision_feature_layer: Optional[Union[int, list[int]]] = None,
        vision_feature_select_strategy: Optional[str] = None,
    ):
        return self.model.get_image_features(
            pixel_values=pixel_values,
            image_sizes=image_sizes,
            vision_feature_layer=vision_feature_layer,
            vision_feature_select_strategy=vision_feature_select_strategy,
        )

    # Make modules available through conditional class for BC
    @property
    def language_model(self):
        return self.model.language_model

    @property
    def vision_tower(self):
        return self.model.vision_tower

    @property
    def multi_modal_projector(self):
        return self.model.multi_modal_projector

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        pixel_values: Optional[torch.FloatTensor] = None,
        image_sizes: Optional[torch.LongTensor] = None,
        pixel_values_videos: Optional[torch.FloatTensor] = None,
        image_sizes_videos: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        vision_feature_layer: Optional[Union[int, list[int]]] = None,
        vision_feature_select_strategy: Optional[str] = None,
        vision_aspect_ratio: Optional[str] = None,
        batch_num_images: Optional[torch.LongTensor] = None,
        labels: Optional[torch.LongTensor] = None,
        use_cache: Optional[bool] = None,
        output_attentions: Optional[bool] = None,
        output_hidden_states: Optional[bool] = None,
        return_dict: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        logits_to_keep: Union[int, torch.Tensor] = 0,
        **kwargs: Unpack[TransformersKwargs],
    ) -> Union[tuple, LlavaOnevisionCausalLMOutputWithPast]:
        r"""
        image_sizes_videos (`torch.LongTensor` of shape `(batch_size, frames, 2)`, *optional*):
            The sizes of the videos in the batch, being (height, width) for each frame in the video.
        vision_aspect_ratio (`str`, *optional*, defaults to `"anyres_max_9"`):
            Aspect ratio used when processong image features. The default value is "anyres_max_9".
        batch_num_images (`torch.LongTensor`, *optional*):
            Number of images in each sample.
        labels (`torch.LongTensor` of shape `(batch_size, sequence_length)`, *optional*):
            Labels for computing the masked language modeling loss. Indices should either be in `[0, ...,
            config.vocab_size]` or -100 (see `input_ids` docstring). Tokens with indices set to `-100` are ignored
            (masked), the loss is only computed for the tokens with labels in `[0, ..., config.vocab_size]`.

        Example:

        ```python
        >>> from PIL import Image
        >>> import requests
        >>> import torch
        >>> from transformers import LlavaOnevisionProcessor, LlavaOnevisionForConditionalGeneration

        >>> model = LlavaOnevisionForConditionalGeneration.from_pretrained("llava-hf/llava-onevision-qwen2-7b-ov-hf", dtype="float16", device_map="cuda:0")
        >>> processor = LlavaOnevisionProcessor.from_pretrained("llava-hf/llava-onevision-qwen2-7b-ov-hf")

        >>> conversation = [
        ...     {
        ...       "role": "user",
        ...       "content": [
        ...           {"type": "text", "text": "What is shown in this image?"},
        ...           {"type": "image"},
        ...         ],
        ...     },
        ... ]
        >>> prompt = processor.apply_chat_template(conversation, add_generation_prompt=True)

        >>> image_file = "http://images.cocodataset.org/val2017/000000039769.jpg"
        >>> raw_image = Image.open(requests.get(image_file, stream=True).raw)
        >>> inputs = processor(text=prompt, images=raw_image, return_tensors='pt').to(0, torch.float16)

        >>> output = model.generate(**inputs, max_new_tokens=20, do_sample=False)
        >>> processor.batch_decode(output, skip_special_tokens=True)[0]
        "user\n\nWhat is shown in this image?\nassistant\ncat"
        ```"""
        # raise "hello world"

        output_attentions = output_attentions if output_attentions is not None else self.config.output_attentions
        output_hidden_states = (
            output_hidden_states if output_hidden_states is not None else self.config.output_hidden_states
        )
        return_dict = return_dict if return_dict is not None else self.config.use_return_dict
        vision_feature_layer = (
            vision_feature_layer if vision_feature_layer is not None else self.config.vision_feature_layer
        )
        vision_feature_select_strategy = (
            vision_feature_select_strategy
            if vision_feature_select_strategy is not None
            else self.config.vision_feature_select_strategy
        )
        vision_aspect_ratio = (
            vision_aspect_ratio if vision_aspect_ratio is not None else self.config.vision_aspect_ratio
        )

        outputs = self.model(
            input_ids=input_ids,
            pixel_values=pixel_values,
            pixel_values_videos=pixel_values_videos,
            image_sizes=image_sizes,
            image_sizes_videos=image_sizes_videos,
            vision_aspect_ratio=vision_aspect_ratio,
            vision_feature_layer=vision_feature_layer,
            vision_feature_select_strategy=vision_feature_select_strategy,
            batch_num_images=batch_num_images,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            use_cache=use_cache,
            output_attentions=output_attentions,
            output_hidden_states=output_hidden_states,
            return_dict=True,
            cache_position=cache_position,
            logits_to_keep=logits_to_keep,
            **kwargs,
        )

        # Sync SemVID stats from the inner model (if present)
        if hasattr(self.model, "fastvid_last_stats"):
            self.fastvid_last_stats = self.model.fastvid_last_stats
        if hasattr(self.model, "last_semantic_prune_coords"):
            self.last_semantic_prune_coords = self.model.last_semantic_prune_coords

        hidden_states = outputs[0]
        # Only compute necessary logits, and do not upcast them to float if we are not computing the loss
        slice_indices = slice(-logits_to_keep, None) if isinstance(logits_to_keep, int) else logits_to_keep
        logits = self.lm_head(hidden_states[:, slice_indices, :])

        loss = None
        if labels is not None:
            loss = self.loss_function(
                logits=logits, labels=labels, vocab_size=self.config.text_config.vocab_size, **kwargs
            )

        return LlavaOnevisionCausalLMOutputWithPast(
            loss=loss,
            logits=logits,
            past_key_values=outputs.past_key_values,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions,
            image_hidden_states=outputs.image_hidden_states,
            video_hidden_states=outputs.video_hidden_states,
        )

    def prepare_inputs_for_generation(
        self,
        input_ids,
        past_key_values=None,
        inputs_embeds=None,
        pixel_values=None,
        image_sizes=None,
        pixel_values_videos=None,
        image_sizes_videos=None,
        attention_mask=None,
        cache_position=None,
        logits_to_keep=None,
        **kwargs,
    ):
        # Overwritten -- in specific circumstances we don't want to forward image inputs to the model

        model_inputs = super().prepare_inputs_for_generation(
            input_ids,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            attention_mask=attention_mask,
            cache_position=cache_position,
            logits_to_keep=logits_to_keep,
            **kwargs,
        )

        if cache_position[0] == 0:
            # If we're in cached decoding stage, pixel values should be None because input ids do not contain special image token anymore
            # Otherwise we need pixel values to be passed to model
            model_inputs["pixel_values"] = pixel_values
            model_inputs["image_sizes"] = image_sizes
            model_inputs["pixel_values_videos"] = pixel_values_videos
            model_inputs["image_sizes_videos"] = image_sizes_videos

        return model_inputs

    @staticmethod
    def _prepare_4d_causal_attention_mask_with_cache_position(
        attention_mask: torch.Tensor,
        sequence_length: int,
        target_length: int,
        dtype: torch.dtype,
        cache_position: torch.Tensor,
        batch_size: int,
        **kwargs,
    ):
        """
        Creates a causal 4D mask of shape `(batch_size, 1, query_length, key_value_length)` from a 2D mask of shape
        `(batch_size, key_value_length)`, or if the input `attention_mask` is already 4D, do nothing.

        Args:
            attention_mask (`torch.Tensor`):
                A 2D attention mask of shape `(batch_size, key_value_length)` or a 4D attention mask of shape
                `(batch_size, 1, query_length, key_value_length)`.
            sequence_length (`int`):
                The sequence length being processed.
            target_length (`int`):
                The target length: when generating with static cache, the mask should be as long as the static cache,
                to account for the 0 padding, the part of the cache that is not filled yet.
            dtype (`torch.dtype`):
                The dtype to use for the 4D attention mask.
            cache_position (`torch.Tensor`):
                Indices depicting the position of the input sequence tokens in the sequence.
            batch_size (`torch.Tensor`):
                Batch size.
        """
        if attention_mask is not None and attention_mask.dim() == 4:
            # In this case we assume that the mask comes already in inverted form and requires no inversion or slicing.
            causal_mask = attention_mask
        else:
            min_dtype = torch.finfo(dtype).min
            causal_mask = torch.full(
                (sequence_length, target_length), fill_value=min_dtype, dtype=dtype, device=cache_position.device
            )
            if sequence_length != 1:
                causal_mask = torch.triu(causal_mask, diagonal=1)
            causal_mask *= torch.arange(target_length, device=cache_position.device) > cache_position.reshape(-1, 1)
            causal_mask = causal_mask[None, None, :, :].expand(batch_size, 1, -1, -1)
            if attention_mask is not None:
                causal_mask = causal_mask.clone()  # copy to contiguous memory for in-place edit
                mask_length = attention_mask.shape[-1]
                padding_mask = causal_mask[:, :, :, :mask_length] + attention_mask[:, None, None, :].to(
                    causal_mask.device
                )
                padding_mask = padding_mask == 0
                causal_mask[:, :, :, :mask_length] = causal_mask[:, :, :, :mask_length].masked_fill(
                    padding_mask, min_dtype
                )

        return causal_mask

    def get_video_features(
        self,
        pixel_values: torch.FloatTensor,
        vision_feature_layer: Optional[Union[int, list[int]]] = None,
        vision_feature_select_strategy: Optional[str] = None,
    ):
        return self.model.get_video_features(
            pixel_values=pixel_values,
            vision_feature_layer=vision_feature_layer,
            vision_feature_select_strategy=vision_feature_select_strategy,
        )


__all__ = ["LlavaOnevisionModel", "LlavaOnevisionForConditionalGeneration", "LlavaOnevisionPreTrainedModel"]
